// login as troels
POST https://localhost:7067/Auth/login
Content-Type: application/json

{ "Username" : "jknr", "Password" : "password" }

###

GET https://localhost:7067/test/authorized
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI5YTYyMmZiNS1lN2FjLTQ4NTctYjVmNC03MWQ2ZTYwMDU2OWMiLCJpYXQiOiIzLzI5LzIwMjMgOToyNTowNyBQTSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJqa25yIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsIkRpc3BsYXlOYW1lIjoiSmFrb2IgUmFzbXVzc2VuIiwiRW1haWwiOiJqYWtvYkBnbWFpbC5jb20iLCJBZ2UiOiIzNCIsIkRvbWFpbiI6ImdtYWlsIiwiU2VjdXJpdHlMZXZlbCI6IjIiLCJleHAiOjE2ODAxMjg3MDcsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvclNlcnZlckFwcENsaWVudCJ9.yTVkZBMuj8cx-3LxH7oZXEYA88hecjR06C8Y1xipSfJ0awIKtoScQI2A-FKAifkFr8orRhBwRlx25D8rI4LtGA

###
GET https://localhost:7067/test/mustbevia
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI5YTYyMmZiNS1lN2FjLTQ4NTctYjVmNC03MWQ2ZTYwMDU2OWMiLCJpYXQiOiIzLzI5LzIwMjMgOToyNTowNyBQTSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJqa25yIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsIkRpc3BsYXlOYW1lIjoiSmFrb2IgUmFzbXVzc2VuIiwiRW1haWwiOiJqYWtvYkBnbWFpbC5jb20iLCJBZ2UiOiIzNCIsIkRvbWFpbiI6ImdtYWlsIiwiU2VjdXJpdHlMZXZlbCI6IjIiLCJleHAiOjE2ODAxMjg3MDcsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvclNlcnZlckFwcENsaWVudCJ9.yTVkZBMuj8cx-3LxH7oZXEYA88hecjR06C8Y1xipSfJ0awIKtoScQI2A-FKAifkFr8orRhBwRlx25D8rI4LtGA

